name: Testes API DemoQA

on:
  push:
    branches: [ main ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman and Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run API tests with Newman
        run: |
          mkdir reports
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,htmlextra,json \
          --reporter-htmlextra-export reports/report.html \
          --reporter-json-export reports/report.json

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: reports/
